services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: rail_data_hub_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/timescaledb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
    name: rail_data_hub_volume