"""
Auto-generated by analysis/geocode_stations.py — REVIEW BEFORE USE.
Maps station display name -> (lat, lon) via OpenStreetMap Nominatim.
"""

STATION_COORDINATES: dict[str, tuple[float, float]] = {
    'Aachen Hbf': (50.767766, 6.091382),  # Aachen Hauptbahnhof, 2a, Bahnhofstraße, Kaiserplatz, Burtscheid, 
    'Albacete - Los Llanos': (38.995092, -1.855915),  # Albacete, Castilla-La Mancha, España
    'Amsterdam Centraal': (52.378901, 4.900581),  # Amsterdam Centraal, Middentunnel, Centrum, Amsterdam, Noord-Holla
    'Ancona': (43.480119, 13.218728),  # Ancona, Marche, Italia
    'Barcelona - Sants': (41.379007, 2.140004),  # Barcelona - Sants, 1-7, Plaça dels Països Catalans, Sants, Sants-
    'Bari Centrale': (41.117950, 16.870240),  # Bari Centrale, 51, Piazza Aldo Moro, Murat, Municipio 1, Bari, Pu
    'Basel Bad Bf': (47.567462, 7.607310),  # Basel Badischer Bahnhof, Bad. Bahnhof-Passage, Hirzbrunnen, Klein
    'Berlin Hbf': (52.525017, 13.369448),  # Berlin Hauptbahnhof, Washingtonplatz, Europacity, Moabit, Mitte, 
    'Bolzano': (46.655930, 11.230183),  # Bolzano - Bozen, Trentino-Alto Adige/Südtirol, Italia
    'Bordeaux St Jean': (44.825523, -0.555650),  # Bordeaux-Saint-Jean, Rue Charles Domercq, Bordeaux, Port de la Lu
    'Bourg-Saint-Maurice': (45.618611, 6.769528),  # Bourg-Saint-Maurice, Albertville, Savoie, Auvergne-Rhône-Alpes, F
    'Bratislava hlavná stanica': (48.158799, 17.106022),  # Bratislava hlavná stanica, 3215, Bratislava-Staré Mesto, okres Br
    'Bremen Hbf': (53.083146, 8.813542),  # Bremen Hauptbahnhof, 15, 16, Bahnhofsplatz, Bahnhofsvorstadt, Mit
    'Brest': (48.390528, -4.486009),  # Brest, Finistère, Bretagne, France métropolitaine, 29200, France
    'Brno hlavní nádraží': (49.191122, 16.613112),  # Brno hlavní nádraží, 418/1, Nádražní, Brno-město, Brno-střed, Brn
    'Brussels-Midi': (50.835775, 4.336054),  # Bruxelles-Midi - Brussel-Zuid, Galerie M - M-galerij, Saint-Gille
    'Budapest-Keleti': (47.500412, 19.083980),  # Budapest-Keleti, 1, Baross tér, Kerepesdűlő, VIII. kerület, Budap
    'Colmar': (48.077752, 7.357964),  # Colmar, Colmar-Ribeauvillé, Haut-Rhin, Collectivité européenne d'
    'Dortmund Hbf': (51.517893, 7.459283),  # Dortmund Hbf, Paul-Winzen-Straße, Innenstadt Nord, Dortmund, Nord
    'Dresden Hbf': (51.040245, 13.732077),  # Dresden Hbf, 4, Wiener Platz, Seevorstadt-Ost/Großer Garten, Seev
    'Düsseldorf Hbf': (51.219734, 6.794302),  # Düsseldorf Hauptbahnhof, Weg Gleis 12, Stadtmitte, Stadtbezirk 1,
    'Frankfurt(Main)Hbf': (50.106654, 8.662581),  # Frankfurt (Main) Hauptbahnhof, Mannheimer Straße, Gallus, Innenst
    'Gdańsk Główny': (54.356434, 18.644195),  # Gdańsk Główny, 2, Podwale Grodzkie, Grodzisko, Stare Miasto, Śród
    'Genova Piazza Principe': (44.417020, 8.921130),  # Genova Piazza Principe, Piazza Acquaverde, Principe, Lagaccio, Ce
    'Graz Hbf': (47.072212, 15.417189),  # Graz Hauptbahnhof, Europaplatz, Katastralgemeinde Lend, Lend, Gra
    'Hamburg Hbf': (53.552984, 10.006757),  # Hamburg Hauptbahnhof, Steintordamm, St. Georg, Hamburg-Mitte, Ham
    'Hendaye': (43.364152, -1.761650),  # Hendaye, Bayonne, Pyrénées-Atlantiques, Nouvelle-Aquitaine, Franc
    'Karlsruhe Hbf': (48.993543, 8.401167),  # Karlsruhe Hauptbahnhof, Bahnhofplatz, Südweststadt Östlicher Teil
    'Kiel Hbf': (54.313473, 10.130965),  # Kiel Hauptbahnhof, 25-27, Sophienblatt, Südfriedhof, Kiel, Schles
    'Koblenz Hbf': (50.350823, 7.589264),  # Koblenz Hbf, Bahnhofplatz, Mitte, Koblenz, Rheinland-Pfalz, 56068
    'Kraków Główny': (50.068424, 19.947886),  # Kraków Główny, Świętego Rafała Kalinowskiego, Wesoła, Stare Miast
    'Köln Hbf': (50.942784, 6.959071),  # Köln Hauptbahnhof, 11, Trankgasse, Martinsviertel, Altstadt-Nord,
    'Lecce': (40.152217, 18.226063),  # Lecce, Puglia, Italia
    'Leipzig Hbf': (51.346552, 12.383086),  # Leipzig Hauptbahnhof, 5, Willy-Brandt-Platz, Zentrum-Ost, Mitte, 
    'Linz Hbf': (48.290241, 14.291862),  # Linz Hauptbahnhof, Verbindungstunnel TS Werk - Hbf Linz, Innere S
    'Lyon toutes gares': (45.748322, 4.825327),  # Lyon-Perrache, Passage France Pejot, Perrache, Lyon 2e Arrondisse
    'Lübeck Hbf': (53.867123, 10.670478),  # Lübeck Hauptbahnhof, 2-6, Am Bahnhof, Sankt Lorenz Süd, Lübeck, S
    'Madrid - Todas las estaciones': (40.404661, -3.688970),  # Madrid-Puerta de Atocha-Almudena Grandes, Calle del Áncora, Palos
    'Marseille St Charles': (43.303263, 5.381193),  # Marseille-Saint-Charles, Square Narvik, Saint-Charles, Marseille 
    'Milano Centrale': (45.485879, 9.204262),  # Milano Centrale, Piazza Duca d'Aosta, Centrale, Municipio 2, Mila
    'Montpellier toutes gares': (43.604246, 3.880322),  # Montpellier Saint-Roch, 1, Place Auguste Gibert, Gares, Centre, M
    'München Hbf': (48.140725, 11.556943),  # München Hauptbahnhof, Paul-Heyse-Unterführung, Klinikviertel, Lud
    'Nantes': (47.218637, -1.554136),  # Nantes, Loire-Atlantique, Pays de la Loire, France métropolitaine
    'Napoli Centrale': (40.853024, 14.273140),  # Napoli Centrale, Corso Meridionale, Rione Vasto, Vicaria, Municip
    'Nice Ville': (43.704784, 7.261832),  # Nice-Ville, Parvis de la Gare, Vernier, Thiers, La Buffa, Nice, A
    'Ostrava hlavní nádraží': (49.850670, 18.267072),  # Ostrava hlavní nádraží, Nádražní, Přívoz, Moravská Ostrava a Přív
    'Ostseebad Binz': (54.401029, 13.607648),  # Binz, Vorpommern-Rügen, Mecklenburg-Vorpommern, 18609, Deutschlan
    'Paris - Toutes les gares': (48.843663, 2.374487),  # Gare de Lyon, Allée de Bercy, Quartier des Quinze-Vingts, Paris 1
    'Paris Est': (48.877098, 2.359491),  # Paris Gare de l'Est, Place du 11 Novembre 1918, Quartier Saint-Vi
    'Passau Hbf': (48.573712, 13.450474),  # Passau Hbf, Obere Bahnhofstraße, Hacklberg, Ries, Passau, Bayern,
    'Perpignan': (42.698530, 2.895312),  # Perpignan, Pyrénées-Orientales, Occitanie, France métropolitaine,
    'Praha hlavní nádraží': (50.082963, 14.436094),  # Praha hlavní nádraží, Wilsonova, Nové Město, obvod Praha 1, Praha
    'Ravenna': (44.364061, 12.059010),  # Ravenna, Emilia-Romagna, Italia
    'Reggio di Calabria Centrale': (38.103566, 15.636148),  # Reggio Calabria Centrale, Via Barlaam da Seminara, Reggio di Cala
    'Rennes': (48.111339, -1.680020),  # Rennes, Ille-et-Vilaine, Bretagne, France métropolitaine, France
    'Roma Termini': (41.901195, 12.501671),  # Roma Termini, Piazza dei Cinquecento, Esquilino, Municipio Roma I
    'Saarbrücken Hbf': (49.241197, 6.990794),  # Saarbrücken Hauptbahnhof, Am Hauptbahnhof, Hauptbahnhof, St. Joha
    'Salerno': (40.419442, 15.310609),  # Salerno, Campania, Italia
    'Sevilla - Santa Justa': (37.392092, -5.975206),  # Sevilla - Santa Justa, Carril Taxi, Huerta de Santa Teresa, San P
    'Strasbourg Ville': (48.569103, 7.752492),  # Strasbourg-Ville (avant 2015), Strasbourg, Bas-Rhin, Collectivité
    'Stuttgart Hbf': (48.784266, 9.182117),  # Stuttgart Hauptbahnhof, 2, Arnulf-Klett-Platz, Hauptbahnhof, Stut
    'Torino Porta Nuova': (45.061892, 7.678369),  # Torino Porta Nuova, Piazza Carlo Felice, Centro, Circoscrizione 1
    'Torino Porta Susa': (45.071576, 7.665855),  # Torino Porta Susa, Corso Inghilterra, Crocetta, Circoscrizione 1,
    'Toulouse Matabiau': (43.611431, 1.454210),  # Toulouse-Matabiau, Boulevard Pierre Semard, Marengo, Faubourg Bon
    'Trieste Centrale': (45.662340, 13.769208),  # Trieste Centrale, Città Nuova-Barriera Nuova-San Vito-Città Vecch
    'Udine': (46.063463, 13.235838),  # Udine / Udin, Udine / Udin / Videm, Friuli-Venezia Giulia, 33100,
    'Valencia - Joaquín Sorolla': (39.460047, -0.381208),  # València Joaquín Sorolla, Carrer de Francisco Largo Caballero, Ar
    'Venezia Santa Lucia': (45.441075, 12.321032),  # Venezia Santa Lucia, Fondamenta Santa Lucia, Cannaregio, Venezia-
    'Warszawa Centralna': (52.228821, 21.003160),  # Warszawa Centralna, 54, Aleje Jerozolimskie, Żelazna Brama, Śródm
    'Wien Hbf': (48.184988, 16.377939),  # Wien Hauptbahnhof, 1, Am Hauptbahnhof, Quartier Belvedere, Katast
    'Wiesbaden Hbf': (50.069831, 8.243985),  # Wiesbaden Hauptbahnhof, Bahnhofsplatz, Südost, Wiesbaden, Hessen,
    'Wrocław Główny': (51.097916, 17.037951),  # Wrocław Główny, tunel boczny, Glinianki, Huby, Wrocław, województ
    'Zaragoza - Delicias': (41.658573, -0.911388),  # Zaragoza-Delicias, 33, Calle Rioja, La Almozara, Zaragoza, Aragón
    'Zürich HB': (47.378101, 8.539364),  # Zürich Hauptbahnhof, Passage Löwenstrasse, City, Altstadt, Zürich
}
